/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_uber_neuropod_NeuropodTensorAllocator */

#ifndef _Included_com_uber_neuropod_NeuropodTensorAllocator
#define _Included_com_uber_neuropod_NeuropodTensorAllocator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_uber_neuropod_NeuropodTensorAllocator
 * Method:    nativeDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_uber_neuropod_NeuropodTensorAllocator_nativeDelete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
