/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_uber_neuropod_LibraryLoader */

#ifndef _Included_com_uber_neuropod_LibraryLoader
#define _Included_com_uber_neuropod_LibraryLoader
#ifdef __cplusplus
extern "C" {
#endif
#undef com_uber_neuropod_LibraryLoader_BUFFER_SIZE
#define com_uber_neuropod_LibraryLoader_BUFFER_SIZE 1048576L
/*
 * Class:     com_uber_neuropod_LibraryLoader
 * Method:    nativeIsLoaded
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_uber_neuropod_LibraryLoader_nativeIsLoaded
  (JNIEnv *, jclass);

/*
 * Class:     com_uber_neuropod_LibraryLoader
 * Method:    nativeExport
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_uber_neuropod_LibraryLoader_nativeExport
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_uber_neuropod_LibraryLoader
 * Method:    nativeSetTestMode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_uber_neuropod_LibraryLoader_nativeSetTestMode
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
