/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_uber_neuropod_NeuropodValue */

#ifndef _Included_com_uber_neuropod_NeuropodValue
#define _Included_com_uber_neuropod_NeuropodValue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_uber_neuropod_NeuropodValue
 * Method:    nativeGetBuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_uber_neuropod_NeuropodValue_nativeGetBuffer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_uber_neuropod_NeuropodValue
 * Method:    nativeToStringList
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_uber_neuropod_NeuropodValue_nativeToStringList
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_uber_neuropod_NeuropodValue
 * Method:    nativeCreateStringTensor
 * Signature: (Ljava/util/List;[JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_uber_neuropod_NeuropodValue_nativeCreateStringTensor
  (JNIEnv *, jclass, jobject, jlongArray, jlong);

/*
 * Class:     com_uber_neuropod_NeuropodValue
 * Method:    nativeAllocate
 * Signature: ([JIJ)J
 */
JNIEXPORT jlong JNICALL Java_com_uber_neuropod_NeuropodValue_nativeAllocate
  (JNIEnv *, jclass, jlongArray, jint, jlong);

/*
 * Class:     com_uber_neuropod_NeuropodValue
 * Method:    nativeGetDims
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_uber_neuropod_NeuropodValue_nativeGetDims
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_uber_neuropod_NeuropodValue
 * Method:    nativeGetTensorType
 * Signature: (J)Lcom/uber/neuropod/TensorType;
 */
JNIEXPORT jobject JNICALL Java_com_uber_neuropod_NeuropodValue_nativeGetTensorType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_uber_neuropod_NeuropodValue
 * Method:    nativeGetNumberOfElements
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_uber_neuropod_NeuropodValue_nativeGetNumberOfElements
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_uber_neuropod_NeuropodValue
 * Method:    nativeDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_uber_neuropod_NeuropodValue_nativeDelete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
