/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_uber_neuropod_NeuropodValueMap */

#ifndef _Included_com_uber_neuropod_NeuropodValueMap
#define _Included_com_uber_neuropod_NeuropodValueMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_uber_neuropod_NeuropodValueMap
 * Method:    nativeDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_uber_neuropod_NeuropodValueMap_nativeDelete
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_uber_neuropod_NeuropodValueMap
 * Method:    nativeNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_uber_neuropod_NeuropodValueMap_nativeNew
  (JNIEnv *, jclass);

/*
 * Class:     com_uber_neuropod_NeuropodValueMap
 * Method:    nativeAddEntry
 * Signature: (Ljava/lang/String;JJ)V
 */
JNIEXPORT void JNICALL Java_com_uber_neuropod_NeuropodValueMap_nativeAddEntry
  (JNIEnv *, jclass, jstring, jlong, jlong);

/*
 * Class:     com_uber_neuropod_NeuropodValueMap
 * Method:    nativeGetValue
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_uber_neuropod_NeuropodValueMap_nativeGetValue
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     com_uber_neuropod_NeuropodValueMap
 * Method:    nativeGetKeyList
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_uber_neuropod_NeuropodValueMap_nativeGetKeyList
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
