/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_uber_neuropod_RuntimeOptions_RuntimeOptionsNative */

#ifndef _Included_com_uber_neuropod_RuntimeOptions_RuntimeOptionsNative
#define _Included_com_uber_neuropod_RuntimeOptions_RuntimeOptionsNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_uber_neuropod_RuntimeOptions_RuntimeOptionsNative
 * Method:    nativeCreate
 * Signature: (ZLjava/lang/String;IZZ)J
 */
JNIEXPORT jlong JNICALL Java_com_uber_neuropod_RuntimeOptions_00024RuntimeOptionsNative_nativeCreate
  (JNIEnv *, jclass, jboolean, jstring, jint, jboolean, jboolean);

/*
 * Class:     com_uber_neuropod_RuntimeOptions_RuntimeOptionsNative
 * Method:    nativeDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_uber_neuropod_RuntimeOptions_00024RuntimeOptionsNative_nativeDelete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
