/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_neuropod_NeuropodValue */

#ifndef _Included_org_neuropod_NeuropodValue
#define _Included_org_neuropod_NeuropodValue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_neuropod_NeuropodValue
 * Method:    nativeToList
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_neuropod_NeuropodValue_nativeToList
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_neuropod_NeuropodValue
 * Method:    nativeCreate
 * Signature: (Ljava/lang/Object;Ljava/util/List;IJ)J
 */
JNIEXPORT jlong JNICALL Java_org_neuropod_NeuropodValue_nativeCreate
  (JNIEnv *, jclass, jobject, jobject, jint, jlong);

/*
 * Class:     org_neuropod_NeuropodValue
 * Method:    nativeGetDims
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_neuropod_NeuropodValue_nativeGetDims
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_neuropod_NeuropodValue
 * Method:    nativeGetTensorType
 * Signature: (J)Lorg/neuropod/TensorType;
 */
JNIEXPORT jobject JNICALL Java_org_neuropod_NeuropodValue_nativeGetTensorType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_neuropod_NeuropodValue
 * Method:    nativeDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_neuropod_NeuropodValue_nativeDelete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
