/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_neuropod_LibraryLoader */

#ifndef _Included_org_neuropod_LibraryLoader
#define _Included_org_neuropod_LibraryLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_neuropod_LibraryLoader
 * Method:    nativeIsLoaded
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_neuropod_LibraryLoader_nativeIsLoaded
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
